### ISSUE TITLE
Release this package to ROS

### ISSUE THREAD

**Issue by reinzor** [aktaylor08/RosbagPandas#11]
Any plans to release this package into ROS and further maintain it? If not, can I release it?

**Comment by reinzor** [comment]
Do you have any plans to continue supporting this package? If not, we will add our fork to the rosdistro.

**Comment by aktaylor08** [comment]
I don't really have the time to keep up support, so I would support a fork
on rosdistro.

**Comment by reinzor** [comment]
Thanks for your reply: fork will be housed here: https://github.com/eurogroep/rosbag_pandas
