### ISSUE TITLE
Convert to ROS package

### ISSUE THREAD

**Issue by reinzor** [aktaylor08/RosbagPandas#8]
Hi, 

I would like to have this package as dependency in one of my projects. I see it is currently a python package via pip but it depends on ROS dependencies: `rosbag` and `rospy`. See also https://github.com/ros/rosdistro/pull/18392#issuecomment-403579207

Would you accept a PR making the package a ROS package? And releasing it into the ROS distro?

**Comment by aktaylor08** [comment]
Yeah. That sounds great

**Comment by reinzor** [comment]
Can I remove the regular python package files?
